from datetime import datetime, timezone
from typing import Dict, Any, List

from app.services.data_service import get_ohlcv_df, get_current_price
from app.services.arima_service import forecast_arima
from app.services.trend_service import forecast_trend
from app.services.technical_service import get_technical_indicators
from app.services.claude_service import get_ai_analysis
from app.utils.cache import cache
from app.config import settings

DISCLAIMER = {
    "en": (
        "All price forecasts are speculative and generated by automated statistical models. "
        "They do not constitute financial advice. Gold prices are subject to significant volatility "
        "and actual prices may differ substantially from any forecast."
    ),
    "ar": (
        "جميع توقعات الأسعار تخمينية وصادرة عن نماذج إحصائية آلية. "
        "لا تُعدّ نصيحةً مالية. تتعرض أسعار الذهب لتقلبات كبيرة وقد تختلف الأسعار الفعلية "
        "اختلافاً جوهرياً عن أي توقع."
    ),
}

# Timeframe definitions
TIMEFRAMES = [
    {"key": "1d",  "label": "Tomorrow",  "trading_days": 1},
    {"key": "3d",  "label": "3 Days",    "trading_days": 3},
    {"key": "1w",  "label": "1 Week",    "trading_days": 5},
    {"key": "1m",  "label": "1 Month",   "trading_days": 21},
    {"key": "6m",  "label": "6 Months",  "trading_days": 126},
    {"key": "1y",  "label": "1 Year",    "trading_days": 252},
]

# Ensemble weights: (arima_weight, trend_weight, technical_weight)
WEIGHTS = {
    1:   (0.50, 0.20, 0.30),
    3:   (0.40, 0.30, 0.30),
    5:   (0.25, 0.45, 0.30),
    21:  (0.10, 0.60, 0.30),
    126: (0.07, 0.65, 0.28),
    252: (0.05, 0.70, 0.25),
}


def _technical_price_target(current_price: float, tech: Dict[str, Any]) -> float:
    """
    Compute a technically-adjusted price target from indicators.
    Nudges current price based on RSI, MACD, and MA alignment.
    """
    adjusted = current_price

    rsi_val = tech.get("rsi", {}).get("value")
    if rsi_val is not None:
        if rsi_val > 70:
            adjusted *= 0.995   # overbought → slight pullback
        elif rsi_val < 30:
            adjusted *= 1.005   # oversold → slight bounce

    macd_signal = tech.get("macd", {}).get("crossover_signal", "neutral")
    if macd_signal == "buy":
        adjusted *= 1.003
    elif macd_signal == "sell":
        adjusted *= 0.997

    # MA alignment
    ma = tech.get("moving_averages", {})
    if ma.get("ma_200") and current_price < ma["ma_200"]:
        adjusted *= 0.998   # below 200MA → bearish lean

    return adjusted


def get_ensemble_forecast(lang: str = "en") -> Dict[str, Any]:
    """
    Compute weighted ensemble forecasts for all timeframes.
    Cached for FORECAST_CACHE_TTL seconds (default 1 hour).
    """
    cache_key = f"ensemble_forecast_{settings.gold_ticker}_{lang}"
    cached = cache.get(cache_key)
    if cached is not None:
        return cached

    df = get_ohlcv_df("2y")
    if df is None or df.empty:
        return {"error": "Unable to fetch gold data for forecasting"}

    close = df["Close"]
    current_price = float(close.iloc[-1])
    price_info = get_current_price()
    change_pct = price_info.get("change_pct", 0.0)

    # Get technical indicators (cached separately)
    tech = get_technical_indicators()

    # Technical price target (same for all horizons — just a signal-based nudge)
    tech_target = _technical_price_target(current_price, tech)

    forecasts = []
    forecast_summary = {}  # for Claude prompt

    for tf in TIMEFRAMES:
        steps = tf["trading_days"]
        w_arima, w_trend, w_tech = WEIGHTS[steps]

        # Run models
        arima_result = forecast_arima(close, steps)
        trend_result = forecast_trend(close, steps)

        arima_price = arima_result["predicted_price"]
        trend_price = trend_result["predicted_price"]

        # Ensemble weighted price
        ensemble_price = (
            arima_price * w_arima +
            trend_price * w_trend +
            tech_target * w_tech
        )
        ensemble_price = round(ensemble_price, 2)

        # Confidence interval: average of model CIs, plus growth with horizon
        ci_low = (
            arima_result["confidence_low"] * w_arima +
            trend_result["confidence_low"] * w_trend +
            (tech_target * 0.97) * w_tech
        )
        ci_high = (
            arima_result["confidence_high"] * w_arima +
            trend_result["confidence_high"] * w_trend +
            (tech_target * 1.03) * w_tech
        )

        price_change = ensemble_price - current_price
        price_change_pct = (price_change / current_price * 100) if current_price else 0.0

        direction = "up" if price_change > 0 else ("down" if price_change < 0 else "flat")

        forecasts.append({
            "timeframe": tf["key"],
            "label": tf["label"],
            "trading_days": steps,
            "predicted_price": ensemble_price,
            "price_change": round(price_change, 2),
            "price_change_pct": round(price_change_pct, 4),
            "confidence_low": round(ci_low, 2),
            "confidence_high": round(ci_high, 2),
            "direction": direction,
            "model_contributions": {
                "arima": {"price": arima_price, "weight": w_arima},
                "trend": {"price": trend_price, "weight": w_trend},
                "technical": {"price": tech_target, "weight": w_tech},
            },
        })

        forecast_summary[tf["label"]] = ensemble_price

    # Get Claude AI analysis (async-like, runs after models)
    ai_analysis = get_ai_analysis(
        current_price=current_price,
        change_pct=change_pct,
        technical_signals=tech,
        forecasts=forecast_summary,
        lang=lang,
    )

    result = {
        "current_price": round(current_price, 2),
        "forecasts": forecasts,
        "ai_analysis": ai_analysis,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "disclaimer": DISCLAIMER.get(lang, DISCLAIMER["en"]),
    }

    cache.set(cache_key, result, settings.forecast_cache_ttl)
    return result
